# miry/kubeadm
FROM alpine

ENV RELEASE="v1.11.0-alpha.2"

ADD https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/kubeadm /bin/kubeadm
ADD https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/kubelet /bin/kubelet
ADD https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/kubectl /bin/kubectl
