FROM centos:latest
MAINTAINER Michael Nikitochkin <miry.sof@gmail.com>

RUN yum install -y deltarpm && \
    yum update -y && \
    yum install -y \
                  wget \
                  unzip \
                  autoconf \
                  bison \
                  flex \
                  gcc \
                  gcc-c++ \
                  kernel-devel \
                  make \
                  m4 \
                  patch \
                  java-1.8.0 \
                  mysql \
                  postgresql-server \
                  git \
                  mercurial
