name: Create & Publish jetthoughts/cimg-ruby to DockerHub & GitHubCR

on:
  pull_request:
    paths:
      - 'cimg-ruby/**'
  workflow_dispatch:
  push:
    paths:
      - 'cimg-ruby/**'
    branches:
      - master
      - support-more-rubies
  schedule:
    - cron: "0 0 */5 * *"

env:
  IMAGE_NAME: jetthoughts/cimg-ruby

jobs:
  build-and-push-image:
    strategy:
      matrix:
        version: [ "3.3", "3.2", "3.1" ]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./cimg-ruby/
          build-args: RUBY_VERSION=${{ matrix.version }}
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.version }}-chrome
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.version }}-chrome
